# Generated by Django 5.2 on 2025-05-11 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_articles_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название категории')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('contact_info', models.CharField(max_length=250, verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название товара')),
                ('description', models.CharField(max_length=250, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('stock_quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('image', models.CharField(default='', max_length=250, verbose_name='Картинка')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturers')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
