# Generated by Django 5.2 on 2025-05-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categories_manufacturers_products_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
    ]
